export const games = [
  { name: "Slot", href: "/slot", tagline: "Catch the biggest Fishes", image: "/images/Slot.png" },
  { name: "Blackjack", href: "/blackjack", tagline: "Beat the dealer", image: "/images/BlackJack.png" },
  { name: "Poker", href: "/poker", tagline: "Read your enemies", image: "/images/Poker.png" },
  { name: "Mines", href: "/mines", tagline: "Find diamonds, avoid mines", image: "/images/Mines.png" },
  { name: "Keno", href: "/keno", tagline: "Pick 10 numbers", image: "/images/Keno.png" },
  { name: "Dragon Tower", href: "/dragontower", tagline: "Climb without hitting traps", image: "/images/DragonTower.png" },
  { name: "Russian Roulette", href: "/russianroulette", tagline: "Risk it all — shoot sequentially", image: "/images/RussianRoulette.png" },
  { name: "Pump", href: "/pump", tagline: "Pump and cash out", image: "/images/Pump.png" },
  { name: "Limbo", href: "/limbo", tagline: "Hit your target multiplier", image: "/images/Limbo.png" },
  { name: "Dice", href: "/dice", tagline: "Roll and set your chance", image: "/images/Dice.png" },
  { name: "Roulette", href: "/roulette", tagline: "Spin the wheel, hit your bets", image: "/images/Roulette.png" },
  { name: "Tarot", href: "/tarot", tagline: "Draw 3 multipliers and multiply them", image: "/images/Tarot.png" },
  { name: "Chicken", href: "/chicken", tagline: "Cross safely for rewards", image: "/images/Chicken.png" },
  { name: "Horse Race", href: "/horserace", tagline: "Choose your horse and sprint", image: "/images/HorseRacing.png" },
  { name: "Cases", href: "/cases", tagline: "Open and reveal rewards", image: "/images/Cases.png" },
  { name: "Diamonds", href: "/diamonds", tagline: "Draw 5 diamonds, hit combos", image: "/images/Diamonds.png" },
  { name: "Crash", href: "/crash", tagline: "Ride the curve and cash out", image: "/images/Crash.png" },
  { name: "Plinko", href: "/plinko", tagline: "Drop and win", image: "/images/Plinko.png" },
  { name: "Bars", href: "/bars", tagline: "Pick 1-5 tiles and sum multipliers", image: "/images/Bars.png" },
  { name: "Spinning Wheel", href: "/spinningwheel", tagline: "Spin and hit a multiplier", image: "/images/SpinningWheel.png" },
  { name: "Darts", href: "/darts", tagline: "Aim for a high score", image: "/images/Darts.png" },
  { name: "Vault", href: "/vault", tagline: "Crack the vault and stack multipliers", image: "/images/Vault.png" },
  { name: "Snakes", href: "/snakes", tagline: "Climb high, dodge snakes", image: "/images/Snakes.png" },
  { name: "Coin Flip", href: "/coinflip", tagline: "Build a streak multiplier", image: "/images/Coinflip.png" },
  { name: "Rock Paper Scissors", href: "/rps", tagline: "Build a streak and cash out", image: "/images/RPS.png" },
  { name: "HiLo", href: "/hilo", tagline: "Wette, ob die nächste Karte höher oder niedriger ist", image: "/images/HiLo.png" },
];
