export const GAME_STATUS_KEYS = [
  "bigbassamazonas",
  "coinflip",
  "poker",
  "mines",
  "roulette",
  "dice",
  "crash",
  "dragontower",
  "pump",
  "diamonds",
  "spinningwheel",
  "keno",
  "limbo",
  "blackjack",
  "horserace",
  "cases",
  "drill",
  "russianroulette",
  "tarot",
  "chicken",
  "snakes",
  "plinko",
  "hilo",
  "rps",
  "bars",
  "vault",
  "darts",
];

export const GAME_LABELS: Record<string, string> = {
  bigbassamazonas: "Big Bass Amazonas",
  coinflip: "Coin Flip",
  poker: "Poker",
  mines: "Mines",
  roulette: "Roulette",
  dice: "Dice",
  crash: "Crash",
  dragontower: "Dragon Tower",
  pump: "Pump",
  diamonds: "Diamonds",
  spinningwheel: "Spinning Wheel",
  keno: "Keno",
  limbo: "Limbo",
  blackjack: "Blackjack",
  horserace: "Horse Race",
  cases: "Cases",
  drill: "Drill",
  russianroulette: "Russian Roulette",
  tarot: "Tarot",
  chicken: "Chicken",
  snakes: "Snakes",
  plinko: "Plinko",
  hilo: "HiLo",
  rps: "Rock Paper Scissors",
  bars: "Bars",
  vault: "Vault",
  darts: "Darts",
};

export const GAME_ROUTE_TO_KEY: Record<string, string> = {
  "/bigbassamazonas": "bigbassamazonas",
  "/coinflip": "coinflip",
  "/poker": "poker",
  "/livepoker": "poker",
  "/mines": "mines",
  "/roulette": "roulette",
  "/dice": "dice",
  "/crash": "crash",
  "/dragontower": "dragontower",
  "/pump": "pump",
  "/diamonds": "diamonds",
  "/spinningwheel": "spinningwheel",
  "/keno": "keno",
  "/limbo": "limbo",
  "/horserace": "horserace",
  "/blackjack": "blackjack",
  "/cases": "cases",
  "/drill": "drill",
  "/russianroulette": "russianroulette",
  "/tarot": "tarot",
  "/chicken": "chicken",
  "/snakes": "snakes",
  "/plinko": "plinko",
  "/hilo": "hilo",
  "/rps": "rps",
  "/bars": "bars",
  "/vault": "vault",
  "/darts": "darts",
};

export const DEFAULT_GAME_STATUS: Record<string, boolean> = GAME_STATUS_KEYS.reduce(
  (acc, key) => {
    acc[key] = true;
    return acc;
  },
  {} as Record<string, boolean>
);

export function getGameKeyFromHref(href: string): string {
  return GAME_ROUTE_TO_KEY[href] ?? href.replace("/", "");
}
